
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

lovelace:
  mode: yaml
  dashboards:
    lovelace-hidden:
      mode: yaml
      title: hidden
      show_in_sidebar: false
      require_admin: true
      filename: hidden.yaml

homeassistant:
  name: Amur
  latitude: 55.7997
  longitude: 37.7835
  unit_system: metric
  time_zone: Europe/Moscow
  
yeelight:
  devices:
    192.168.2.218:
      name: livingroom_ceiling_1
      model: ceiling4
    192.168.2.219:
      name: livingroom_ceiling_2
      model: ceiling4
    192.168.2.232:
      name: livingroom_strip
      model: strip1
    192.168.2.213:
      name: bedroom_ceiling
      model: ceiling4
    192.168.2.231:
      name: bedroom_strip
      model: strip1


 
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
