title: Home111
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.yeelight_ceiling4_0x00000000112f8a4d_nightlight
      - entity: person.ruslan
      - entity: sensor.hacs
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - sensor.rt_n66w_b_sent
          - sensor.rt_n66w_packets_received
          - sensor.rt_n66w_packets_sent
          - sensor.rt_n66w_kib_s_received
          - sensor.rt_n66w_kib_s_sent
          - sensor.rt_n66w_packets_s_received
          - sensor.rt_n66w_packets_s_sent
          - sensor.rt_n66w_b_received
        title: Hallway
      - type: entities
        entities:
          - sensor.xiaomi_gateway_illuminance
          - light.xiaomi_gateway_light
        title: Kitchen
      - type: alarm-panel
        entity: alarm_control_panel.xiaomi_gateway_alarm
      - type: entities
        entities:
          - light.yeelight_ceiling4_0x00000000112f8a4d
          - light.yeelight_ceiling4_0x00000000112f8a4d_ambilight
          - light.yeelight_ceiling4_0x00000000112f8a4d_nightlight
        title: Light
      - type: weather-forecast
        entity: weather.home