apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-homeassistant-amur
spec:
  storageClassName: directpv-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi