#auth:
#  reset_admin_password: true
mqtt:
  host: mosquitto
  port: 1883
  user: homeassistant
  password: FLS3GD8Qc8xJWp
#detectors:
#  ov_0:
#    type: openvino
#    device: CPU
#  ov_1:
#    type: openvino
#    device: CPU
record:
  enabled: True
  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 180
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
snapshots:
  enabled: True
  retain:
    default: 180
review:
  alerts:
    labels:
      - person
go2rtc:
  streams:
    gateway:
      - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.3.76:554/Streaming/Channels/101
    canopy_left:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.3.68:554/Streaming/Channels/101#video=copy#audio=aac
    canopy_main:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.3.73:554/Streaming/Channels/101#video=copy#audio=aac
    court:
      - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.3.227:554/Streaming/Channels/101
    garden:
      - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.3.62:554/Streaming/Channels/101
    basement:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.3.17:554/Streaming/Channels/101#video=copy#audio=aac
cameras:
  gateway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gateway
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 1
  canopy_left:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/canopy_left
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 1
  canopy_main:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/canopy_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 1
  court:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/court
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 1
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      fps: 1
  basement:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/basement
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 1