apiVersion: v1
kind: Service
metadata:
  name: amur
  namespace: homeassistant
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: NodePort
  ports:
  - port: 8123
    nodePort: 30017
  selector:
    app: amur