- alias: brownout_on
  initial_state: on
  trigger:
  - entity_id: switch.solar_charge
    platform: state
    to: unavailable
  - entity_id: switch.solar_bypass
    platform: state
    to: unavailable
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.solar_charge
          state: unavailable
        - condition: state
          entity_id: switch.solar_bypass
          state: unavailable
        - condition: state
          entity_id: switch.outlet_01 #fridge
          state: unavailable
        - condition: state
          entity_id: switch.outlet_02
          state: unavailable
  action:
    - service: "input_select.select_option"
      target:
        entity_id: input_select.scene_mati
      data:
        option: 'brownout'
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.voltage
              below: 12.5
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.outlet_06
    - action: persistent_notification.create
      data:
        notification_id: "1000"
        message: "It is power off now in Martinez!"
        title: "Brownout!"
    - action: notify.mobile_app_sm_s908e
      data:
        message: "It is power off now in Martinez."
        title: "Brownout!"
    - action: notify.mobile_app_sm_s938b
      data:
        message: "It is power off now in Martinez."
        title: "Brownout!"

- alias: brownout_off
  initial_state: on
  trigger:
  - entity_id: switch.solar_charge
    platform: state
    to: "on"
  - entity_id: switch.solar_bypass
    platform: state
    to: "on"
  condition:
    - condition: state
      entity_id: input_select.scene_mati
      state: "brownout"
  action:
    - service: "input_select.select_option"
      target:
        entity_id: input_select.scene_mati
      data:
        option: 'normal'
    - service: switch.turn_on
      target:
        entity_id: switch.outlet_06
    - action: persistent_notification.dismiss
      data:
        notification_id: "1000"
    - action: notify.mobile_app_sm_s908e
      data:
        message: "Doreco came back."
        title: "Lights ON!"
    - action: notify.mobile_app_sm_s938b
      data:
        message: "Doreco came back."
        title: "Lights ON!"

- alias: brownout_battery_low
  initial_state: on
  trigger:
    - platform: numeric_state
      entity_id: sensor.voltage
      below: 12.5
  condition:
    - condition: state
      entity_id: input_select.scene_mati
      state: "brownout"
    - condition: state
      entity_id: switch.outlet_06
      state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.outlet_06

- alias: solar_bypass_refresh
  initial_state: on
  triggers:
    - trigger: time_pattern
      hours: "*"
      minutes: "*"
      seconds: /10
  condition:
    - condition: state
      entity_id: sensor.solar_bypass_power
      state: "unknown"
  actions:
    - action: button.press
      metadata: { }
      data: { }
      target:
        entity_id: button.solar_bypass_refresh_sensors

- alias: solar_output_refresh
  initial_state: on
  triggers:
    - trigger: time_pattern
      hours: "*"
      minutes: "*"
      seconds: /10
  condition:
    - condition: state
      entity_id: sensor.solar_output_power
      state: "unknown"
  actions:
    - action: button.press
      metadata: { }
      data: { }
      target:
        entity_id: button.solar_output_refresh_sensors

- alias: solar_all_refresh
  initial_state: on
  triggers:
    - trigger: time_pattern
      hours: "*"
      minutes: /20
      seconds: "*"
  actions:
    - action: homeassistant.reload_config_entry
      data:
        entity_id: switch.solar_bypass
    - action: homeassistant.reload_config_entry
      data:
        entity_id: switch.solar_output

#- alias: mikrotik_entity_refresh
#  initial_state: on
#  triggers:
#    - trigger: time_pattern
#      hours: "*"
#      minutes: "*"
#      seconds: 0
#  actions:
#    - action: homeassistant.reload_config_entry
#      data:
#        entity_id: sensor.mikrotik_hex_captive_portal_clients
