- alias: brownout_on
  initial_state: on
  trigger:
  - entity_id: switch.solar_charge
    platform: state
    to: unavailable
  - entity_id: switch.solar_bypass
    platform: state
    to: unavailable
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.solar_charge
          state: unavailable
        - condition: state
          entity_id: switch.solar_bypass
          state: unavailable
  action:
    - service: "input_select.select_option"
      target:
        entity_id: input_select.scene_mati
      data:
        option: 'brownout'
    - action: persistent_notification.create
      data:
        notification_id: "1000"
        message: "It is power off now in Martinez!"
        title: "Brownout!"
    - action: notify.mobile_app_sm_s908e
      data:
        message: "It is power off now in Martinez."
        title: "Brownout!"
    - action: notify.mobile_app_sm_s938b
      data:
        message: "It is power off now in Martinez."
        title: "Brownout!"

- alias: brownout_off
  initial_state: on
  trigger:
  - entity_id: switch.solar_charge
    platform: state
    to: "on"
  - entity_id: switch.solar_bypass
    platform: state
    to: "on"
  condition:
    - condition: state
      entity_id: input_select.scene_mati
      state: "brownout"
  action:
    - service: "input_select.select_option"
      target:
        entity_id: input_select.scene_mati
      data:
        option: 'normal'
    - action: persistent_notification.dismiss
      data:
        notification_id: "1000"
    - action: notify.mobile_app_sm_s908e
      data:
        message: "Doreco came back."
        title: "Lights ON!"
    - action: notify.mobile_app_sm_s938b
      data:
        message: "Doreco came back."
        title: "Lights ON!"

- alias: power_refresh
  initial_state: on
  triggers:
    - trigger: time_pattern
      hours: "*"
      minutes: "*"
      seconds: /20
  actions:
    - action: button.press
      metadata: { }
      data: { }
      target:
        entity_id: button.solar_bypass_refresh_sensors
    - action: button.press
      metadata: { }
      data: { }
      target:
        entity_id: button.solar_output_refresh_sensors
