default_config:

logger:
  default: info
#  logs:
#    custom_components.miwifi: debug

# Hide built-in sidebar entries
map:
  show_in_sidebar: false
history:
  show_in_sidebar: false
logbook:
  show_in_sidebar: false
media_source:
  show_in_sidebar: false
energy:
  show_in_sidebar: false
todo:
  show_in_sidebar: false
shopping_list:
  show_in_sidebar: false

input_select:
  scene_mati:
    name: Scene Mati
    options:
      - 'brownout'
      - 'normal'

lovelace:
  mode: yaml
  resources:
    - url: /local/advanced-camera-card/advanced-camera-card.js
      type: module
    - url: /local/multiple-entity-row/multiple-entity-row.js?v=4.5.1
      type: module
  dashboards:
    lovelace-storage:
      mode: yaml
      title: storage
      show_in_sidebar: true
      require_admin: false
      filename: ui-storage.yaml

homeassistant:
  name: Mati
  latitude: 55.7997
  longitude: 37.7835
  unit_system: metric
  time_zone: Asia/Manila
  currency: PHP
  country: PH

#scene: !include scenes.yaml
automation: !include automation.yaml
template: !include template.yaml
#script: !include scripts.yaml
