default_config:
  mobile_app:
  person:
  automation:
  script:
  scene:
  webhook:

logger:
  default: warning

lovelace:
  mode: yaml
  resources:
    - url: /local/advanced-camera-card/advanced-camera-card.js
      type: module
    - url: /local/multiple-entity-row/multiple-entity-row.js?v=4.5.1
      type: module
  dashboards:
    lovelace-storage:
      mode: yaml
      title: storage
      show_in_sidebar: true
      require_admin: false
      filename: ui-storage.yaml

template:
  - trigger:
      - platform: webhook
        webhook_id: -Q-2r2VOyBx89C6BicNoaRHsQ
        allowed_methods: POST
        local_only: false
    sensor:
      - name: "Speedtest Download"
        state: "{{ (trigger.json.download / 1024 / 1024) | round(2) }}"
        state_class: measurement
        unit_of_measurement: "Mbps"
      - name: "Speedtest Upload"
        state: "{{ (trigger.json.upload / 1024 / 1024) | round(2) }}"
        state_class: measurement
        unit_of_measurement: "Mbps"
      - name: "Speedtest Ping"
        state: "{{ trigger.json.ping | round(2) }}"
        state_class: measurement
        unit_of_measurement: "ms"
      - name: "Speedtest Packet Loss"
        state: "{{ trigger.json.packetLoss }}"
        state_class: measurement
        unit_of_measurement: "%"
      - name: "Speedtest ISP"
        state: "{{ trigger.json.isp }}"
      - name: "Speedtest Result URL"
        state: "{{ trigger.json.speedtest_url }}"

homeassistant:
  name: Mati
  latitude: 55.7997
  longitude: 37.7835
  unit_system: metric
  time_zone: Europe/Moscow
  currency: PHP
  country: PH

automation: !include automations.yaml
#script: !include scripts.yaml