sensor:

  - name: "mikrotik_device_person"
    icon: mdi:wifi-star
    state_class: total
    state: "{{ 
      integration_entities('mikrotik_router') | 
      select('match', 'device_tracker\\.') | 
      reject('match', 'device_tracker\\.(smart|camera|wifi|server)\\_') |
      select('is_state', ['home', 'not_home']) |
      list | count }}"

  - name: "mikrotik_device_smart"
    icon: mdi:wifi-star
    state_class: total
    state: "{{ 
      integration_entities('mikrotik_router') | 
      select('match', 'device_tracker\\.(smart|wifi)\\_') | 
      select('is_state', 'home') |
      list | count }}"

  - name: "mikrotik_device_away"
    icon: mdi:wifi-star
    state_class: total
    state: "{{ 
      integration_entities('mikrotik_router') | 
      select('match', 'device_tracker\\.') | 
      select('is_state', 'not_home') |
      list | count }}"


binary_sensor:

  - name: "scene_is_brownout"
    state: "{{ is_state('input_select.scene_mati', 'brownout') }}"
