sensor:

  - name: "mikrotik_device_person"
    icon: mdi:wifi-star
    state_class: measurement
    state: "{{ 
      integration_entities('mikrotik_router') | 
      select('match', 'device_tracker\\.') | 
      reject('match', 'device_tracker\\.(smart|camera|wifi|server)\\_') |
      select('is_state', 'home') |
      list | count }}"

  - name: "mikrotik_device_smart"
    icon: mdi:wifi-star
    state_class: measurement
    state: "{{ 
      integration_entities('mikrotik_router') | 
      select('match', 'device_tracker\\.(smart|camera|wifi|server)\\_') | 
      select('is_state', 'home') |
      list | count }}"