title: Home
views:

  - title: Cameras
    cards:

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.madam
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.backyard
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_back
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_front
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.stairway
            live_provider: go2rtc

  - title: Storage
    cards:
      - type: entities
        title: Equipment
        entities:
        - entity: switch.power_meter
          type: custom:multiple-entity-row
          name: Cameras
          toggle: true
          entities:
            - entity: sensor.power_meter_current
              name: current
            - entity: sensor.power_meter_power
              name: power
            - entity: sensor.power_meter_voltage
              name: voltage
  #          - entity: sensor.power_meter_cpu_temperature
  #            name: temperature

      - type: entities
        title: Solar Station
        entities:
        - entity: switch.solar_charge
          type: custom:multiple-entity-row
          name: Doreco Charge
          toggle: true
          entities:
            - entity: sensor.solar_charge_current
              name: current
            - entity: sensor.solar_charge_power
              name: power
            - entity: sensor.solar_charge_voltage
              name: voltage
        - entity: switch.solar_bypass_api
          type: custom:multiple-entity-row
          name: Doreco Bypass
          toggle: true
          entities:
            - entity: sensor.solar_bypass_api_current
              name: current
            - entity: sensor.solar_bypass_api_power
              name: power
            - entity: sensor.solar_bypass_api_voltage
              name: voltage
        - entity: switch.solar_output_api
          type: custom:multiple-entity-row
          name: Solar Output
          toggle: true
          entities:
            - entity: sensor.solar_output_api_current
              name: current
            - entity: sensor.solar_output_api_power
              name: power
            - entity: sensor.solar_output_api_voltage
              name: voltage

      - type: entities
        title: Air
        entities:
          - entity: sensor.storage_co2_air_quality
            name: Index
          - entity: sensor.storage_co2_carbon_dioxide
            name: Carbon Dioxide
          - entity: sensor.storage_co2_carbon_dioxide
            name: Carbon Monoxide
          - entity: sensor.storage_co2_carbon_monoxide
            name: Formaldehyde
          - entity: sensor.storage_co2_humidity
            name: Humidity
          - entity: sensor.storage_co2_pm_0_3
            name: PM_0.3
          - entity: sensor.storage_co2_pm1
            name: PM_1
          - entity: sensor.storage_co2_pm10
            name: PM_10
          - entity: sensor.storage_co2_pm2_5
            name: PM_2.5
          - entity: sensor.storage_co2_temperature
            name: Temperature
          - entity: sensor.storage_co2_volatile_organic_compounds
            name: Volatile Organic Compounds
          - entity: sensor.storage_co2_battery
            name: Battery