title: Home
views:

  - title: Cameras
    cards:

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.madam
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.backyard
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_back
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_front
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.stairway
            live_provider: go2rtc

  - title: Storage
    cards:

      - entity: switch.meter
        type: custom:multiple-entity-row
        name: Power Meter
        toggle: true
        entities:
          - entity: sensor.meter_current
            name: current
          - entity: sensor.meter_power
            name: power
          - entity: sensor.meter_voltage
            name: voltage

      - entity: switch.charge
        type: custom:multiple-entity-row
        name: Doreco Charge
        toggle: true
        entities:
          - entity: sensor.charge_current
            name: current
          - entity: sensor.charge_power
            name: power
          - entity: sensor.charge_voltage
            name: voltage

      - entity: switch.bypass
        type: custom:multiple-entity-row
        name: Doreco Bypass
        toggle: true
        entities:
          - entity: sensor.bypass_phase_a_current
            name: current
          - entity: sensor.bypass_phase_a_power
            name: power
          - entity: sensor.bypass_phase_a_voltage
            name: voltage

      - entity: switch.solar
        type: custom:multiple-entity-row
        name: Solar Power
        toggle: true
        entities:
          - entity: sensor.solar_phase_a_current
            name: current
          - entity: sensor.solar_phase_a_power
            name: power
          - entity: sensor.solar_phase_a_voltage
            name: voltage

      - type: entities
        title: Temperature
        entities:
          - entity: sensor.co2_air_quality
            name: Index
          - entity: sensor.co2_carbon_dioxide
            name: Carbon Dioxide
          - entity: sensor.co2_carbon_dioxide
            name: Carbon Monoxide
          - entity: sensor.co2_carbon_monoxide
            name: Formaldehyde
          - entity: sensor.co2_humidity
            name: Humidity
          - entity: sensor.co2_pm_0_3
            name: PM_0.3
          - entity: sensor.co2_pm1
            name: PM_1
          - entity: sensor.co2_pm10
            name: PM_10
          - entity: sensor.co2_pm2_5
            name: PM_2.5
          - entity: sensor.co2_temperature
            name: Temperature
          - entity: sensor.co2_volatile_organic_compounds
            name: Volatile Organic Compounds
          - entity: sensor.co2_battery
            name: Battery