title: Home
views:

  - title: Public
    cards:

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_front
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.room01
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.room05
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.room08
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.justin
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.backyard
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.stairway
            live_provider: go2rtc


  - title: Internet
    cards:

      - type: iframe
        name: Speedtest
        url: http://192.168.4.201:8081/
        aspect_ratio: 100%
        allow: fullscreen


  - title: AlwaysON
    cards:

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_back
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_front
            live_provider: go2rtc


  - title: Private
    cards:

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gate_back
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.madam
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.livingroom
            live_provider: go2rtc
