title: Home
views:

  - title: Storage
    cards:
      - type: entities
        title: Equipment
        entities:
        - entity: switch.power_meter
          type: custom:multiple-entity-row
          name: Cameras
          toggle: true
          entities:
            - entity: sensor.power_meter_current
              name: current
            - entity: sensor.power_meter_power
              name: power
            - entity: sensor.power_meter_voltage
              name: voltage
  #          - entity: sensor.power_meter_cpu_temperature
  #            name: temperature

      - type: entities
        title: Solar Station
        entities:
        - entity: switch.solar_charge
          type: custom:multiple-entity-row
          name: Doreco Charge
          toggle: true
          entities:
            - entity: sensor.solar_charge_current
              name: current
            - entity: sensor.solar_charge_power
              name: power
            - entity: sensor.solar_charge_voltage
              name: voltage
        - entity: switch.solar_bypass
          type: custom:multiple-entity-row
          name: Doreco Bypass
          toggle: true
          entities:
            - icon: mdi:refresh
              tap_action:
                action: call-service
                service: button.press
                service_data:
                  entity_id: button.solar_bypass_refresh_sensors
            - entity: sensor.solar_bypass_current
              name: current
            - entity: sensor.solar_bypass_power
              name: power
            - entity: sensor.solar_bypass_voltage
              name: voltage
        - entity: switch.solar_output
          type: custom:multiple-entity-row
          name: Solar Output
          toggle: true
          entities:
            - icon: mdi:refresh
              tap_action:
                action: call-service
                service: button.press
                service_data:
                  entity_id: button.solar_output_refresh_sensors
            - entity: sensor.solar_output_current
              name: current
            - entity: sensor.solar_output_power
              name: power
            - entity: sensor.solar_output_voltage
              name: voltage

      - type: entities
        title: Air
        entities:
          - entity: sensor.storage_co2_air_quality
            name: Index
          - entity: sensor.storage_co2_carbon_dioxide
            name: Carbon Dioxide
          - entity: sensor.storage_co2_carbon_dioxide
            name: Carbon Monoxide
          - entity: sensor.storage_co2_carbon_monoxide
            name: Formaldehyde
          - entity: sensor.storage_co2_humidity
            name: Humidity
          - entity: sensor.storage_co2_pm_0_3
            name: PM_0.3
          - entity: sensor.storage_co2_pm1
            name: PM_1
          - entity: sensor.storage_co2_pm10
            name: PM_10
          - entity: sensor.storage_co2_pm2_5
            name: PM_2.5
          - entity: sensor.storage_co2_temperature
            name: Temperature
          - entity: sensor.storage_co2_volatile_organic_compounds
            name: Volatile Organic Compounds
          - entity: sensor.storage_co2_battery
            name: Battery

      - type: entities
        title: Network
        entities:
          - entity: sensor.mikrotik_hex_cpu_load
            name: CPU
          - entity: sensor.mikrotik_hex_memory_usage
            name: RAM
          - entity: sensor.mikrotik_hex_hdd_usage
            name: HDD
          - entity: sensor.mikrotik_hex_board_temperature
            name: Board
          - entity: sensor.mikrotik_hex_cpu_temperature
            name: CPU
