apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-docker
  namespace: homeassistant
spec:
  serviceAccountName: deployer
  workflowMetadata:
    annotations:
      workflows.argoproj.io/title: '**build-docker**-{{`{{ workflow.parameters.service }}`}}'
      workflows.argoproj.io/description: '`{{`{{ workflow.parameters.env }}`}}`'
  ttlStrategy:
    secondsAfterCompletion: 604800
  entrypoint: docker
  onExit: telegram
  arguments:
    parameters:
      - name: project
        value: iot
      - name: application
        value: homeassistant
      - name: service
        enum:
          - amur
          - dacha
          - mati
      - name: env
        value: master

  templates:

    - name: docker
      steps:
        - - name: docker
            templateRef:
              name: docker
              template: process
              clusterScope: true
            arguments:
              parameters:
                - name: repo
                  value: home
                - name: project
                  value: "{{`{{ workflow.parameters.project }}`}}"
                - name: application
                  value: "{{`{{ workflow.parameters.application }}`}}"
                - name: service
                  value: "{{`{{ workflow.parameters.service }}`}}"
                - name: env
                  value: "{{`{{ workflow.parameters.env }}`}}"

    - name: telegram
      steps:
        - - name: telegram
            templateRef:
              name: telegram
              template: send
              clusterScope: true