apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
  namespace: {{ .Release.Namespace }}
  labels:
    app: go2rtc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go2rtc
  template:
    metadata:
      labels:
        app: go2rtc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kube03
      imagePullSecrets:
        - name: registry
      containers:
      - name: go2rtc
        image: alexxit/go2rtc:latest
        imagePullPolicy: Always
        command: ["/bin/sh","-ce"]
        args:
          - "echo $CONFIG &&
             cat > /config/go2rtc.yaml<< echo $CONFIG"
        env:
          - name: CONFIG
            valueFrom:
              configMapKeyRef:
                name: config
                key: config
        livenessProbe:
          httpGet:
            path: /
            port: 1984
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
