apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
  namespace: frigate
  labels:
    app: go2rtc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go2rtc
  template:
    metadata:
      labels:
        app: go2rtc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kube03
      imagePullSecrets:
        - name: registry
      containers:
      - name: go2rtc
        image: alexxit/go2rtc:latest
        imagePullPolicy: Always
        command: ["/bin/sh","-ce"]
        args:
          - "cat > /config/go2rtc.yaml<< EOF
              streams:
                elevators: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.111:80
                vestibule: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.113:80
                intercom: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.116:80
                balcony: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.117:80
              EOF"
        livenessProbe:
          httpGet:
            path: /
            port: 1984
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
