apiVersion: v1
kind: Service
metadata:
  name: go2rtc-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 1984
    targetPort: 1984
    protocol: TCP
  selector:
    app: go2rtc
---
apiVersion: v1
kind: Service
metadata:
  name: go2rtc-rtsp
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8554
    targetPort: 8554
    protocol: TCP
  selector:
    app: go2rtc