title: Home
views:

  - title: Hallway
    cards:

      - type: entities
        entities:
          - entity: alarm_control_panel.6490c176b86e_alarm
            name: alarm
          - entity: switch.6490c176b86e_alarm_trigger
            name: alarm
        title: Gateway

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_1_motion
            name: motion
          - entity: sensor.hallway_motion_1_battery
            name: battery
          - entity: sensor.hallway_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_2_motion
            name: motion
          - entity: sensor.hallway_motion_2_battery
            name: battery
          - entity: sensor.hallway_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: entities
        entities:
          - entity: binary_sensor.walkthrough_motion_1_motion
            name: motion
          - entity: sensor.walkthrough_motion_1_battery
            name: battery
          - entity: sensor.walkthrough_motion_1_illuminance
            name: illuminance
        title: Motion3

      - type: entities
        entities:
          - entity: light.hallway_light_1_light
            name: point1
          - entity: light.hallway_light_2_light
            name: point2
          - entity: light.hallway_light_3_light
            name: point3
          - entity: light.hallway_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: light.hallway_light_4_light
            name: point1
          - entity: light.walkthrough_light_1_light
            name: point2
          - entity: light.walkthrough_light_2_light
            name: point3
          - entity: light.walkthrough_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: sensor.hallway_button_action
            name: action
          - entity: sensor.hallway_button_battery
            name: battery
        title: Button

      - type: entities
        entities:
          - entity: sensor.hallway_vibration_action
            name: action
          - entity: sensor.hallway_vibration_battery
            name: battery
        title: Vibration

      - type: entities
        entities:
          - entity: button.xiaomi_ov31cn_0c3c_start_sweep
            name: Start
          - entity: button.xiaomi_ov31cn_0c3c_stop_and_gocharge
            name: Stop and go Charge
          - entity: button.xiaomi_ov31cn_0c3c_pause_sweeping
            name: Pause
          - entity: button.xiaomi_ov31cn_0c3c_continue_sweep
            name: Resume
          - entity: select.xiaomi_ov31cn_0c3c_sweep_mop_type
            name: Mode
          - entity: select.xiaomi_ov31cn_0c3c_mode
            name: Suction
          - entity: select.xiaomi_ov31cn_0c3c_clean_times
            name: Number of times
          - entity: sensor.xiaomi_ov31cn_0c3c_battery_level
            name: Battery level
          - entity: sensor.xiaomi_ov31cn_0c3c_charging_state
            name: Charging State
          - entity: sensor.xiaomi_ov31cn_0c3c_mop_life_level
            name: Mop Status
        title: Vacuum

      - type: entities
        entities:
          - entity: lock.hallway_lock
            name: Lock
        title: Lock

      - type: picture-entity
        entity: camera.hallway
        name: video
        show_name: false
        show_state: false

      - type: iframe
        name: Speedtest
        url: http://192.168.2.242:8081/
        aspect_ratio: 75%