order:
  - item: /home
    match: href
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: history
    hide: true
  - item: logbook
    hide: true
  - item: media
    hide: true
  - item: miwifi
    hide: true
  - item: to-do
    hide: true
