services:
  homeassistant:
    container_name: homeassistant
    image: registry.ibragimov.pw/home/homeassistant/dacha:master
    volumes:
      - /docker/home-homeassistant-dacha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
