apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-frigate-amur
  namespace: frigate
spec:
  storageClassName: directpv-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi