apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-frigate-amur-media
  namespace: frigate
spec:
  storageClassName: directpv-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-frigate-amur-config
  namespace: frigate
spec:
  storageClassName: directpv-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi