apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-homeassistant-amur-pvc
spec:
  storageClassName: directpv-min-io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi