default_config:

recorder:
  db_url: !env_var MYSQL_URL

# Text to speech
tts:
  - platform: google_translate

logger:
  default: debug

lovelace:
  mode: yaml
  resources:
    - url: /custom_components/advanced-camera-card/advanced-camera-card.js
      type: module
  dashboards:
    lovelace-bedroom:
      mode: yaml
      title: bedroom
      show_in_sidebar: true
      require_admin: false
      filename: ui-bedroom.yaml
    lovelace-livingroom:
      mode: yaml
      title: livingroom
      show_in_sidebar: true
      require_admin: false
      filename: ui-livingroom.yaml
    lovelace-kitchen:
      mode: yaml
      title: kitchen
      show_in_sidebar: true
      require_admin: false
      filename: ui-kitchen.yaml
    lovelace-hallway:
      mode: yaml
      title: hallway
      show_in_sidebar: true
      require_admin: false
      filename: ui-hallway.yaml
    lovelace-bathroom:
      mode: yaml
      title: bathroom
      show_in_sidebar: true
      require_admin: false
      filename: ui-bathroom.yaml
    lovelace-toilet:
      mode: yaml
      title: toilet
      show_in_sidebar: true
      require_admin: false
      filename: ui-toilet.yaml
    lovelace-balcony:
      mode: yaml
      title: balcony
      show_in_sidebar: true
      require_admin: false
      filename: ui-balcony.yaml

homeassistant:
  name: Amur
  latitude: 55.7997
  longitude: 37.7835
  unit_system: metric
  time_zone: Europe/Moscow
  currency: RUB
  country: RU

input_select:
  scene_amur:
    name: Scene Amur
    options:
      - 'bright'
      - 'romantic'
      - 'work'
      - 'away'
      - 'sleep'
    icon: mdi:format-list-bulleted

#  gateway:
#    192.168.2.217:
#      name: hallway_gateway
#      model: lumi.gateway.mgl03
#      token: 6f794172766f6a4a45674f6c7032334c / 5463376734326d64426f31724971564c
#      key: VdGkKtZlgeJJc9UN

yeelight:
  devices:
    192.168.2.219:
      name: livingroom_ceiling_1
      model: ceiling4
      nightlight_switch_type: light
    192.168.2.218:
      name: livingroom_ceiling_2
      model: ceiling4
      nightlight_switch_type: light
    192.168.2.232:
      name: livingroom_strip
      model: strip1
    192.168.2.213:
      name: bedroom_ceiling
      model: ceiling4
      nightlight_switch_type: light
    192.168.2.231:
      name: bedroom_strip
      model: strip1

xiaomi_gateway3:
  devices:
    "6490c176b86e":
      name: hallway_gateway # not work
    # bedroom
    "0x00158d0004117b14":
      entity_name: bedroom_curtain
    "0x00158d00045fa45e":
      entity_name: bedroom_motion_1
    "0x00158d0003f134b1":
      entity_name: bedroom_temperature
    # livingroom
    "0x00158d0004117c61":
      entity_name: livingroom_curtain
    "0x00158d00045f6eb9":
      entity_name: livingroom_motion_1
    "0x00158d00015dcc71":
      entity_name: livingroom_power_5
    "0x00158d00015f0deb":
      entity_name: livingroom_power_6
    # kitchen
    "087cbe88ab96":
      entity_name: kitchen_kettle
    "50ec50ca3317":
      entity_name: kitchen_bulb_1
    "50ec50c8bbf8":
      entity_name: kitchen_bulb_2
    "50ec50ca32e0":
      entity_name: kitchen_bulb_3
    "50ec50c8c5a1":
      entity_name: kitchen_bulb_4
    "50ec50c9b92e":
      entity_name: kitchen_bulb_5
    "50ec50ca4891":
      entity_name: kitchen_bulb_6
    "1708917941049368576":
      entity_name: kitchen_chandelier
    "50ec50d838c8":
      entity_name: kitchen_light_1
    "50ec50d6ab9d":
      entity_name: kitchen_light_2
    "1243803959987204096":
      entity_name: kitchen_lights
    "0x00158d0003cb8f6f":
      entity_name: kitchen_relay_1
    "0x00158d000476cc4f":
      entity_name: kitchen_motion_1
    "0x00158d00045f3ec3":
      entity_name: kitchen_motion_2
    "0x00158d00044a1810":
      entity_name: kitchen_temperature
    # hallway
    "50ec50d897bc":
      entity_name: hallway_light_1
    "50ec50d8b136":
      entity_name: hallway_light_2
    "50ec50d8889d":
      entity_name: hallway_light_3
    "1246405497222508544":
      entity_name: hallway_lights
    "50ec50d88656":
      entity_name: hallway_light_4
    "50ec50d5e2e3":
      entity_name: walkthrough_light_1
    "50ec50d86c7b":
      entity_name: walkthrough_light_2
    "1246410642622177281":
      entity_name: walkthrough_lights
    "0x00158d00047ba4d8":
      entity_name: hallway_motion_1
    "0x00158d00042cfa44":
      entity_name: hallway_motion_2
    "0x00158d00047d447d":
      entity_name: walkthrough_motion_1
    "0x00158d000312ec22":
      entity_name: hallway_vibration
    "0x00158d0003457d27":
      entity_name: hallway_button
    "0x00158d0003402818":
      entity_name: elevators_button
    # bathroom
    "0x00158d0003f3ebe0":
      entity_name: bathroom_relay_1
    "0x00158d00040d34fe":
      entity_name: bathroom_relay_2
    "0x00158d00035aa8e1":
      entity_name: bathroom_moisture
    "0x00158d000476cc04":
      entity_name: bathroom_motion_1
    "50ec50d849cf":
      entity_name: bathroom_light_1
    "50ec50d888ad":
      entity_name: bathroom_light_2
    "50ec50d838cc":
      entity_name: bathroom_light_3
    "1243817367251902464":
      entity_name: bathroom_lights
    # toilet
    "0x00158d000444ed42":
      entity_name: toilet_relay_1
    "50ec50d8a05d":
      entity_name: toilet_light_1
    "50ec50d8869e":
      entity_name: toilet_light_2
    "1246411413024075776":
      entity_name: toilet_lights
    "0x00158d000476d283":
      entity_name: toilet_motion_1
    # balcony
    "0x00158d0003f0fc26":
      entity_name: balcony_temperature

lock:
  - platform: zk_teco
    name: hallway_lock
    host: 192.168.2.227
    password: 245578
    protocol: udp




#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - name: kitchen_hub
#      host: 192.168.2.210
#      key: 268v4556jdn0xehg


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#camera: !include cameras.yaml
