title: Home
views:

  - title: Hallway
    cards:

      - type: entities
        entities:
          - entity: alarm_control_panel.6490c176b86e_alarm
            name: alarm
          - entity: switch.6490c176b86e_alarm_trigger
            name: alarm
        title: Gateway

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_1_motion
            name: motion
          - entity: sensor.hallway_motion_1_battery
            name: battery
          - entity: sensor.hallway_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_2_motion
            name: motion
          - entity: sensor.hallway_motion_2_battery
            name: battery
          - entity: sensor.hallway_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: entities
        entities:
          - entity: binary_sensor.walkthrough_motion_1_motion
            name: motion
          - entity: sensor.walkthrough_motion_1_battery
            name: battery
          - entity: sensor.walkthrough_motion_1_illuminance
            name: illuminance
        title: Motion3

      - type: entities
        entities:
          - entity: light.hallway_light_1_light
            name: point1
          - entity: light.hallway_light_2_light
            name: point2
          - entity: light.hallway_light_3_light
            name: point3
          - entity: light.hallway_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: light.hallway_light_4_light
            name: point1
          - entity: light.walkthrough_light_1_light
            name: point2
          - entity: light.walkthrough_light_2_light
            name: point3
          - entity: light.walkthrough_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: sensor.hallway_button_action
            name: action
          - entity: sensor.hallway_button_battery
            name: battery
        title: Button

      - type: entities
        entities:
          - entity: sensor.hallway_vibration_action
            name: action
          - entity: sensor.hallway_vibration_battery
            name: battery
        title: Vibration

      - type: entities
        entities:
          - entity: vacuum.viomi_v7_2f27_robot_cleaner
            name: clean
          - entity: sensor.viomi_v7_2f27_battery_level
            name: battery
          - entity: sensor.viomi_v7_2f27_clean_area
            name: area
          - entity: sensor.viomi_v7_2f27_clean_time
            name: time
          - entity: sensor.viomi_v7_2f27_hypa_life
            name: hypa
          - entity: sensor.viomi_v7_2f27_main_brush_life
            name: main_brush
          - entity: sensor.viomi_v7_2f27_mop_life
            name: mop
          - entity: sensor.viomi_v7_2f27_side_brush_life
            name: side_brush
          - entity: sensor.viomi_v7_2f27_status
            name: status
        title: Vacuum

      - type: entities
        entities:
          - entity: lock.hallway_lock
            name: Lock
        title: Lock

      - type: picture-entity
        entity: camera.hallway
        name: video
        show_name: false
        show_state: false
