- alias: moving_livingroom
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.livingroom_motion_1_motion
      to: "off"
      for:
        minutes: 1
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.livingroom_strip
  mode: single


- alias: moving_bedroom
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.bedroom_motion_1_motion
      to: "off"
      for:
        minutes: 1
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "sleep"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.bedroom_strip
  mode: single


- alias: moving_hallway
  initial_state: on
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_motion_1_motion
        - binary_sensor.hallway_motion_2_motion
      to: "on"
    - platform: state
      entity_id:
        - binary_sensor.hallway_motion_1_motion
        - binary_sensor.hallway_motion_2_motion
      to: "off"
      for:
        minutes: 3
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.hallway_lights_light
  mode: single


- alias: moving_walkthrough
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.walkthrough_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.walkthrough_motion_1_motion
      to: "off"
      for:
        seconds: 1
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.walkthrough_lights_light
  mode: single


- alias: moving_kitchen_1
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.kitchen_motion_1_motion
      to: "off"
      for:
        minutes: 1
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "switch.turn_{{ trigger.to_state.state }}"
      data:
        entity_id: switch.kitchen_relay_1_channel_1
  mode: single

- alias: moving_kitchen_2
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_2_motion
      to: "on"
    - platform: state
      entity_id:
        - binary_sensor.kitchen_motion_1_motion
        - binary_sensor.kitchen_motion_2_motion
      to: "off"
      for:
        minutes: 5
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.kitchen_lights_light
  mode: single


- alias: moving_bathroom
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.bathroom_motion_1_motion
      to: "off"
      for:
        minutes: 5
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.bathroom_lights_light
  mode: single


- alias: moving_toilet_1
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.toilet_motion_1_motion
      to: "off"
      for:
        minutes: 5
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: light.toilet_lights_light
  mode: single


- alias: moving_toilet_2
  initial_state: on
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_motion_1_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.toilet_motion_1_motion
      to: "off"
      for:
        minutes: 5
  conditions:
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "bright"
    - not:
      - condition: state
        entity_id: input_select.scene_amur
        state: "romantic"
  action:
    - service: "switch.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: switch.toilet_relay_1_channel_1
  mode: single


- alias: button_bell
  initial_state: on
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.elevators_button_action
          click_type: hold
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.elevators_button_action
          click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.elevators_button_action
          click_type: double
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.elevators_button_action
          click_type: triple
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.elevators_button_action
          click_type: quadruple
  action:
    sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.6490c176b86e_alarm_trigger
      - delay:
          seconds: 2
      - service: switch.turn_off
        target:
          entity_id: switch.6490c176b86e_alarm_trigger
  mode: single


- alias: scene_input
  trigger:
    platform: state
    entity_id: input_select.scene_amur
    to: # null to triggers on all state changes
  action:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: >
            {% if is_state('input_select.scene_amur','bright') %}
              scene.bright
            {% elif is_state('input_select.scene_amur','romantic') %}
              scene.romantic
            {% elif is_state('input_select.scene_amur','work') %}
              scene.work
            {% elif is_state('input_select.scene_amur','away') %}
              scene.away
            {% elif is_state('input_select.scene_amur','sleep') %}
              scene.sleep
            {% else %}
              scene.away
            {% endif %}
      - delay:
          minutes: 30
      - service: switch.turn_off
        data:
          entity_id: switch.bathroom_relay_1_channel_1
      - service: switch.turn_off
        data:
          entity_id: switch.bathroom_relay_1_channel_2


- alias: button_bright
  initial_state: on
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.hallway_button_action
          click_type: single
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.scene_amur
      data:
        option: 'bright'
  mode: single


- alias: button_romantic
  initial_state: on
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.hallway_button_action
          click_type: double
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.scene_amur
      data:
        option: 'romantic'
  mode: single


- alias: button_work
  initial_state: on
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.hallway_button_action
          click_type: triple
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.scene_amur
      data:
        option: 'work'
  mode: single


- alias: button_away
  initial_state: on
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.hallway_button_action
          click_type: quadruple
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.scene_amur
      data:
        option: 'away'
  mode: single


- alias: button_sleep
  initial_state: on
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
          entity_id: sensor.hallway_button_action
          click_type: hold
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.scene_amur
      data:
        option: 'sleep'
  mode: single