- alias: moving livingroom on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom_motion_1_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.livingroom_ceiling_2

- alias: moving livingroom off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom_motion_1_motion
    to: 'off'
    for:
      seconds: 1
  action:
    service: light.turn_off
    entity_id: light.livingroom_ceiling_2


- alias: moving hallway on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.hallway_motion_1_motion
      - binary_sensor.hallway_motion_2_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.hallway_lights

- alias: moving hallway off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hallway_motion_1_motion
      - binary_sensor.hallway_motion_2_motion
    to: 'off'
    for:
      seconds: 1
  action:
    service: light.turn_off
    entity_id:
      - light.hallway_lights


- alias: moving walkthrough on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.walkthrough_motion_1_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.walkthrough_light

- alias: moving walkthrough off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion_1_motion
    to: 'off'
    for:
      seconds: 1
  action:
    service: light.turn_off
    entity_id:
      - light.walkthrough_light


- alias: moving kitchen on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.kitchen_motion_1_motion
      - binary_sensor.kitchen_motion_2_motion
    to: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.kitchen_lights
    - service: switch.turn_on
      entity_id: switch.kitchen_relay_1_channel_1

- alias: moving kitchen off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.kitchen_motion_1_motion
      - binary_sensor.kitchen_motion_2_motion
    to: 'off'
    for:
      seconds: 1
  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen_lights
        - light.50ec50d6ab9d_light
    - service: switch.turn_off
      entity_id: switch.kitchen_relay_1_channel_1


- alias: moving bathroom on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_1_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.bathroom_lights

- alias: moving bathroom off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_1_motion
    to: 'off'
    for:
      seconds: 1
  action:
    service: light.turn_off
    entity_id:
      - light.bathroom_lights


- alias: moving toilet on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion_1_motion
    to: 'on'
  action:
    - service: light.turn_on
      entity_id:
      - light.toilet_lights
    - service: switch.turn_on
      entity_id: switch.toilet_relay_1_channel_2

- alias: moving toilet off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion_1_motion
    to: 'off'
    for:
      seconds: 1
  action:
    - service: light.turn_off
      entity_id:
        - light.toilet_lights
    - service: switch.turn_off
      entity_id: switch.toilet_relay_1_channel_2