- platform: onvif
  name: elevators_camera
  host: 192.168.2.111
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: hallway_camera
  host: 192.168.2.112
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: vestibule_camera
  host: 192.168.2.113
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: livingroom_camera
  host: 192.168.2.114
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: kitchen_camera
  host: 192.168.2.115
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: intercom_camera
  host: 192.168.2.116
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: balcony_camera
  host: 192.168.2.117
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
- platform: onvif
  name: bedroom_camera
  host: 192.168.2.118
  port: 80
  username: homeassistant
  password: aP5n8XdebfKeDn
