#recorder:
#  db_url: !env_var MYSQL_URL

# Text to speech
tts:
  - platform: google_translate

logger:
  default: debug

lovelace:
  mode: yaml
  dashboards:
    lovelace-hidden:
      mode: yaml
      title: hidden
      show_in_sidebar: false
      require_admin: true
      filename: hidden.yaml

homeassistant:
  name: Amur
  latitude: 55.7997
  longitude: 37.7835
  unit_system: metric
  time_zone: Europe/Moscow
  currency: RUB
  country: RU
  
yeelight:
  devices:
    192.168.2.218:
      name: livingroom_ceiling_1
      model: ceiling4
    192.168.2.219:
      name: livingroom_ceiling_2
      model: ceiling4
    192.168.2.232:
      name: livingroom_strip
      model: strip1
    192.168.2.213:
      name: bedroom_ceiling
      model: ceiling4
    192.168.2.231:
      name: bedroom_strip
      model: strip1
#    192.168.2.217:
#      name: hallway_gateway
#      model: lumi.gateway.mgl03
#      token: 6f794172766f6a4a45674f6c7032334c
#      key: VdGkKtZlgeJJc9UN

xiaomi_gateway3:
  devices:
    "64:90:C1:76:B8:6E":  # match device by IEEE or MAC
      model: lumi.gateway.mgl03
      name: hallway_gateway


#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - name: kitchen_hub
#      host: 192.168.2.210
#      key: 268v4556jdn0xehg
    

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
