title: Home
views:
  - title: Main
    cards:
      - type: grid
        cards:
          - type: button
            entity: scene.bright
            name: Bright
            show_name: true
            show_icon: true
            tap_action:
              action: call-service
              service: input_select.select_option
              target:
                entity_id:
                  - input_select.scene_amur
              data:
                option: 'bright'
          - type: button
            entity: scene.romantic
            name: Romantic
            show_name: true
            show_icon: true
            tap_action:
              action: call-service
              service: input_select.select_option
              target:
                entity_id:
                  - input_select.scene_amur
              data:
                option: 'romantic'
          - type: button
            entity: scene.work
            name: Work
            show_name: true
            show_icon: true
            tap_action:
              action: call-service
              service: input_select.select_option
              target:
                entity_id:
                  - input_select.scene_amur
              data:
                option: 'work'
          - type: button
            entity: scene.away
            name: Away
            show_name: true
            show_icon: true
            tap_action:
              action: call-service
              service: input_select.select_option
              target:
                entity_id:
                  - input_select.scene_amur
              data:
                option: 'away'
          - type: button
            entity: scene.sleep
            name: Sleep
            show_name: true
            show_icon: true
            tap_action:
              action: call-service
              service: input_select.select_option
              target:
                entity_id:
                  - input_select.scene_amur
              data:
                option: 'sleep'
          - type: entity
            entity: input_select.scene_amur
            name: scene

      - type: picture-entity
        entity: camera.vestibule_camera_mainstream
        show_name: false
        show_state: false

      - type: picture-entity
        entity: camera.192_168_2_111
        show_name: false
        show_state: false

      - type: picture-entity
        entity: camera.intercom_camera_mainstream
        show_name: false
        show_state: false

  - title: Lights
      - type: entities
        entities:
          - entity: light.bedroom_ceiling
            name: bedroom_ceiling
          - entity: light.bedroom_ceiling_nightlight
            name: bedroom_nightlight
          - entity: light.bedroom_ceiling_ambilight
            name: bedroom_ambilight
          - entity: light.bedroom_strip
            name: bedroom_strip
          - entity: light.livingroom_ceiling_1
            name: livingroom_ceiling_1
          - entity: light.livingroom_ceiling_1_nightlight
            name: livingroom_nightlight_1
          - entity: light.livingroom_ceiling_1_ambilight
            name: livingroom_ambilight_1
          - entity: light.livingroom_ceiling_2
            name: livingroom_ceiling_2
          - entity: light.livingroom_ceiling_2_nightlight
            name: livingroom_nightlight_2
          - entity: light.livingroom_ceiling_2_ambilight
            name: livingroom_ambilight_2
          - entity: light.livingroom_strip
            name: livingroom_strip
          - entity: light.kitchen_lights_light
            name: kitchen_lights
          - entity: light.kitchen_chandelier_light
            name: kitchen_chandelier
          - entity: switch.kitchen_relay_1_channel_1
            name: kitchen_strip
          - entity: light.bathroom_lights_light
            name: bathroom_lights
          - entity: light.toilet_lights_light
            name: toilet_lights
          - entity: light.walkthrough_lights_light
            name: walkthrough_lights
          - entity: light.hallway_lights_light
            name: hallway_lights
          - entity: light.hallway_lights_light
            name: hallway_lights
        title: Light
