title: Home
views:




  - title: Main
    cards:

      - type: entities
        entities:
          - entity: sensor.0x158d00044a0171_temperature
            name: temperature
          - entity: sensor.0x158d00044a0171_humidity
            name: humidity
          - entity: sensor.0x158d00044a0171_pressure
            name: pressure
          - entity: sensor.0x158d00044a0171_battery
            name: battery
        title: Temperature




  - title: Bedroom
    cards:
    
      - type: entities
        entities:
          - entity: light.bedroom_ceiling
            name: ceiling
          - entity: light.bedroom_ceiling_ambilight
            name: ambilight
          - entity: binary_sensor.bedroom_ceiling_nightlight
            name: nightlight
          - entity: light.bedroom_strip
            name: strip
        title: Light

      - type: entities
        entities:
          - entity: cover.bedroom_curtain_motor
            name: motor
        title: Curtain

      - type: entities
        entities:
          - entity: binary_sensor.bedroom_motion_1_motion
            name: motion
          - entity: sensor.bedroom_motion_1_battery
            name: battery
          - entity: sensor.bedroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: sensor.bedroom_temperature
            name: temperature
          - entity: sensor.bedroom_temperature_humidity
            name: humidity
          - entity: sensor.bedroom_temperature_pressure
            name: pressure
          - entity: sensor.bedroom_temperature_battery
            name: battery
        title: Temperature




  - title: Livingroom
    cards:
        
      - type: entities
        entities:
          - entity: light.livingroom_ceiling_1
            name: ceiling_1
          - entity: light.livingroom_ceiling_1_ambilight
            name: ambilight_1
          - entity: light.livingroom_ceiling_2
            name: ceiling_2
          - entity: light.livingroom_ceiling_2_ambilight
            name: ambilight_2
          - entity: light.livingroom_strip
            name: strip
        title: Light

      - type: entities
        entities:
          - entity: cover.livingroom_curtain_motor
            name: motor
        title: Curtain

      - type: entities
        entities:
          - entity: binary_sensor.livingroom_motion_1_motion
            name: motion
          - entity: sensor.livingroom_motion_1_battery
            name: battery
          - entity: sensor.livingroom_motion_1_illuminance
            name: illuminance
        title: Motion




  - title: Hallway
    cards:

      - type: entities
        entities:
          - entity: alarm_control_panel.6490c176b86e_alarm
            name: alarm
          - entity: switch.6490c176b86e_alarm_trigger
            name: alarm
        title: Gateway

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_1_motion
            name: motion
          - entity: sensor.hallway_motion_1_battery
            name: battery
          - entity: sensor.hallway_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_2_motion
            name: motion
          - entity: sensor.hallway_motion_2_battery
            name: battery
          - entity: sensor.hallway_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_3_motion
            name: motion
          - entity: sensor.hallway_motion_3_battery
            name: battery
          - entity: sensor.hallway_motion_3_illuminance
            name: illuminance
        title: Motion3

      - type: entities
        entities:
          - entity: light.hallway_light_1_light
            name: point1
          - entity: light.hallway_light_2_light
            name: point2
          - entity: light.hallway_light_3_light
            name: point3
          - entity: light.hallway_light_4_light
            name: point4
          - entity: light.hallway_light_5_light
            name: point5
          - entity: light.hallway_light_6_light
            name: point6
        title: Light

      - type: entities
        entities:
          - entity: sensor.hallway_vibration_action
            name: Action
          - entity: sensor.hallway_vibration_battery
            name: battery
        title: Vibration




  - title: Kitchen
    cards:

      - type: entities
        entities:
          - entity: sensor.kitchen_kettle_state
            name: State
          - entity: binary_sensor.kitchen_kettle_power
            name: Power
          - entity: sensor.kitchen_kettle_temperature
            name: Temperature
        title: Kettle

      - type: entities
        entities:
          - entity: light.kitchen_light_1_light
            name: point1
          - entity: light.kitchen_light_2_light
            name: point2
        title: Light
        
      - type: entities
        entities:
          - entity: light.kitchen_bulb_1_light
            name: bulb1
          - entity: light.kitchen_bulb_2_light
            name: bulb2
          - entity: light.kitchen_bulb_3_light
            name: bulb3
          - entity: light.kitchen_bulb_4_light
            name: bulb4
          - entity: light.kitchen_bulb_5_light
            name: bulb5
          - entity: light.kitchen_bulb_6_light
            name: bulb6
          - entity: light.kitchen_chandelier_light
            name: group
        title: chandelier

      - type: entities
        entities:
          - entity: switch.kitchen_relay_1_channel_1
            name: Channel1
          - entity: switch.kitchen_relay_1_channel_2
            name: Channel2
          - entity: sensor.kitchen_relay_1_current
            name: Current
          - entity: sensor.kitchen_relay_1_energy
            name: Energy
          - entity: sensor.kitchen_relay_1_power
            name: Power
          - entity: sensor.kitchen_relay_1_voltage
            name: Voltage
        title: Ledline

      - type: entities
        entities:
          - entity: binary_sensor.kitchen_motion_1_motion
            name: motion
          - entity: sensor.kitchen_motion_1_battery
            name: battery
          - entity: sensor.kitchen_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.kitchen_motion_2_motion
            name: motion
          - entity: sensor.kitchen_motion_2_battery
            name: battery
          - entity: sensor.kitchen_motion_2_illuminance
            name: illuminance
        title: Motion2




  - title: Toilet
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.toilet_motion_1_motion
            name: motion
          - entity: sensor.toilet_motion_1_battery
            name: battery
          - entity: sensor.toilet_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.toilet_light_1_light
            name: point1
          - entity: light.toilet_light_2_light
            name: point2
        title: Light

      - type: entities
        entities:
          - entity: switch.toilet_relay_1_channel_1
            name: Channel1
          - entity: switch.toilet_relay_1_channel_2
            name: Channel2
          - entity: sensor.toilet_relay_1_action
            name: Action
          - entity: sensor.toilet_relay_1_current
            name: Current
          - entity: sensor.toilet_relay_1_energy
            name: Energy
          - entity: sensor.toilet_relay_1_power
            name: Power
          - entity: sensor.toilet_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_moisture
            name: moisture
          - entity: sensor.bathroom_moisture_battery
            name: battery
        title: WaterLeak




  - title: Bathroom
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_motion_1_motion
            name: motion
          - entity: sensor.bathroom_motion_1_battery
            name: battery
          - entity: sensor.bathroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.bathroom_light_1_light
            name: point1
          - entity: light.bathroom_light_2_light
            name: point2
          - entity: light.bathroom_light_3_light
            name: point3
          - entity: light.bathroom_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: switch.bathroom_relay_1_channel_1
            name: Channel1
          - entity: switch.bathroom_relay_1_channel_2
            name: Channel2
          - entity: sensor.bathroom_relay_1_current
            name: Current
          - entity: sensor.bathroom_relay_1_energy
            name: Energy
          - entity: sensor.bathroom_relay_1_power
            name: Power
          - entity: sensor.bathroom_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: switch.bathroom_relay_2_channel_1
            name: Channel1
          - entity: switch.bathroom_relay_2_channel_2
            name: Channel2
          - entity: sensor.bathroom_relay_2_action
            name: Current
          - entity: sensor.bathroom_relay_2_energy
            name: Energy
          - entity: sensor.bathroom_relay_2_power
            name: Power
          - entity: sensor.bathroom_relay_2_voltage
            name: Voltage
        title: Towelheat



  - title: Balcony
    cards:

      - type: entities
        entities:
          - entity: sensor.balcony_temperature
            name: temperature
          - entity: sensor.balcony_temperature_humidity
            name: humidity
          - entity: sensor.balcony_temperature_pressure
            name: pressure
          - entity: sensor.balcony_temperature_battery
            name: battery
        title: Temperature