title: Home
views:



# -------------------------------------------------------------
# -------------------------main--------------------------------
# -------------------------------------------------------------
  - title: Main
    cards:
      - type: grid
        cards:
          - type: button
            entity: scene.romantic
            name: Romantic
            show_name: true
            show_icon: true
            tap_action:
              action: toggle
          - type: button
            entity: scene.bright
            name: Bright
            show_name: true
            show_icon: true
            tap_action:
              action: toggle
          - type: button
            entity: scene.away
            name: Away
            show_name: true
            show_icon: true
            tap_action:
              action: toggle

      - type: entities
        entities:
          - entity: light.bedroom_ceiling
            name: bedroom_ceiling
          - entity: light.bedroom_ceiling_nightlight
            name: bedroom_nightlight
          - entity: light.bedroom_ceiling_ambilight
            name: bedroom_ambilight
          - entity: light.bedroom_strip
            name: bedroom_strip
          - entity: light.livingroom_ceiling_1
            name: livingroom_ceiling_1
          - entity: light.livingroom_ceiling_1_nightlight
            name: livingroom_nightlight_1
          - entity: light.livingroom_ceiling_1_ambilight
            name: livingroom_ambilight_1
          - entity: light.livingroom_ceiling_2
            name: livingroom_ceiling_2
          - entity: light.livingroom_ceiling_2_nightlight
            name: livingroom_nightlight_2
          - entity: light.livingroom_ceiling_2_ambilight
            name: livingroom_ambilight_2
          - entity: light.livingroom_strip
            name: livingroom_strip
          - entity: light.kitchen_lights_light
            name: kitchen_lights
          - entity: light.kitchen_chandelier_light
            name: kitchen_chandelier
          - entity: switch.kitchen_relay_1_channel_1
            name: kitchen_strip
          - entity: light.bathroom_lights_light
            name: bathroom_lights
          - entity: light.toilet_lights_light
            name: toilet_lights
          - entity: light.walkthrough_lights_light
            name: walkthrough_lights
          - entity: light.hallway_lights_light
            name: hallway_lights
          - entity: light.hallway_lights_light
            name: hallway_lights
        title: Light

      - type: picture-entity
        entity: camera.vestibule_camera_mainstream
        show_name: false
        show_state: false

      - type: picture-entity
        entity: camera.192_168_2_111
        show_name: false
        show_state: false

      - type: picture-entity
        entity: camera.intercom_camera_mainstream
        show_name: false
        show_state: false


# -------------------------------------------------------------
# -----------------------bedroom-------------------------------
# -------------------------------------------------------------
  - title: Bedroom
    cards:
    
      - type: entities
        entities:
          - entity: light.bedroom_ceiling
            name: ceiling
          - entity: light.bedroom_ceiling_nightlight
            name: nightlight
          - entity: light.bedroom_ceiling_ambilight
            name: ambilight
          - entity: binary_sensor.bedroom_ceiling_nightlight
            name: nightlight
          - entity: light.bedroom_strip
            name: strip
        title: Light

      - type: entities
        entities:
          - entity: cover.bedroom_curtain_motor
            name: motor
        title: Curtain

      - type: entities
        entities:
          - entity: binary_sensor.bedroom_motion_1_motion
            name: motion
          - entity: sensor.bedroom_motion_1_battery
            name: battery
          - entity: sensor.bedroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: sensor.bedroom_temperature
            name: temperature
          - entity: sensor.bedroom_temperature_humidity
            name: humidity
          - entity: sensor.bedroom_temperature_pressure
            name: pressure
          - entity: sensor.bedroom_temperature_battery
            name: battery
        title: Temperature

      - type: picture-entity
        entity: camera.bedroom_camera_mainstream
        show_name: false
        show_state: false


# -------------------------------------------------------------
# ----------------------livingroom-----------------------------
# -------------------------------------------------------------
  - title: Livingroom
    cards:
        
      - type: entities
        entities:
          - entity: light.livingroom_ceiling_1
            name: ceiling_1
          - entity: light.livingroom_ceiling_1_nightlight
            name: nightlight_1
          - entity: light.livingroom_ceiling_1_ambilight
            name: ambilight_1
          - entity: light.livingroom_ceiling_2
            name: ceiling_2
          - entity: light.livingroom_ceiling_2_nightlight
            name: nightlight_2
          - entity: light.livingroom_ceiling_2_ambilight
            name: ambilight_2
          - entity: light.livingroom_strip
            name: strip
        title: Light

      - type: entities
        entities:
          - entity: cover.livingroom_curtain_motor
            name: motor
        title: Curtain

      - type: entities
        entities:
          - entity: binary_sensor.livingroom_motion_1_motion
            name: motion
          - entity: sensor.livingroom_motion_1_battery
            name: battery
          - entity: sensor.livingroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: sensor.livingroom_air_temperature
            name: temperature
          - entity: sensor.livingroom_air_humidity
            name: humidity
          - entity: sensor.livingroom_air_co2
            name: co2
          - entity: sensor.livingroom_air_pm10
            name: pm10
          - entity: sensor.livingroom_air_pm25
            name: pm25
          - entity: sensor.livingroom_air_tvoc
            name: tvoc
          - entity: sensor.livingroom_air_battery
            name: battery
        title: Air

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_5bd0_switch_status
            name: status
          - entity: light.chuangmi_212a01_5bd0_switch_status
            name: light
          - entity: sensor.chuangmi_212a01_5bd0_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_5bd0_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_5bd0_temperature
            name: power
        title: Power_eGPU

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_f148_switch_status
            name: status
          - entity: light.chuangmi_212a01_f148_switch_status
            name: light
          - entity: sensor.chuangmi_212a01_f148_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_f148_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_f148_temperature
            name: power
        title: Power_LCD

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_d2fd_switch_status
            name: status
          - entity: light.chuangmi_212a01_d2fd_switch_status
            name: light
          - entity: sensor.chuangmi_212a01_d2fd_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_d2fd_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_d2fd_temperature
            name: power
        title: Power_Table

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_690a_switch_status
            name: status
          - entity: light.chuangmi_212a01_690a_switch_status
            name: light
          - entity: sensor.chuangmi_212a01_690a_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_690a_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_690a_temperature
            name: power
        title: Power_MOTU

      - type: picture-entity
        entity: camera.livingroom_camera_mainstream
        name: video
        show_name: false
        show_state: false


# -------------------------------------------------------------
# -----------------------hallway-------------------------------
# -------------------------------------------------------------
  - title: Hallway
    cards:

      - type: entities
        entities:
          - entity: alarm_control_panel.6490c176b86e_alarm
            name: alarm
          - entity: switch.6490c176b86e_alarm_trigger
            name: alarm
        title: Gateway

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_1_motion
            name: motion
          - entity: sensor.hallway_motion_1_battery
            name: battery
          - entity: sensor.hallway_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_2_motion
            name: motion
          - entity: sensor.hallway_motion_2_battery
            name: battery
          - entity: sensor.hallway_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: entities
        entities:
          - entity: binary_sensor.walkthrough_motion_1_motion
            name: motion
          - entity: sensor.walkthrough_motion_1_battery
            name: battery
          - entity: sensor.walkthrough_motion_1_illuminance
            name: illuminance
        title: Motion3

      - type: entities
        entities:
          - entity: light.hallway_light_1_light
            name: point1
          - entity: light.hallway_light_2_light
            name: point2
          - entity: light.hallway_light_3_light
            name: point3
          - entity: light.hallway_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: light.hallway_light_4_light
            name: point1
          - entity: light.walkthrough_light_1_light
            name: point2
          - entity: light.walkthrough_light_2_light
            name: point3
          - entity: light.walkthrough_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: sensor.hallway_button_action
            name: action
          - entity: sensor.hallway_button_battery
            name: battery
        title: Button

      - type: entities
        entities:
          - entity: sensor.hallway_vibration_action
            name: action
          - entity: sensor.hallway_vibration_battery
            name: battery
        title: Vibration

      - type: entities
        entities:
          - entity: vacuum.viomi_v7_2f27_robot_cleaner
            name: clean
          - entity: sensor.viomi_v7_2f27_battery_level
            name: battery
          - entity: sensor.viomi_v7_2f27_clean_area
            name: area
          - entity: sensor.viomi_v7_2f27_clean_time
            name: time
          - entity: sensor.viomi_v7_2f27_hypa_life
            name: hypa
          - entity: sensor.viomi_v7_2f27_main_brush_life
            name: main_brush
          - entity: sensor.viomi_v7_2f27_mop_life
            name: mop
          - entity: sensor.viomi_v7_2f27_side_brush_life
            name: side_brush
          - entity: sensor.viomi_v7_2f27_status
            name: status
        title: Vacuum

      - type: entities
        entities:
          - entity: lock.hallway_lock
            name: Lock
        title: Lock

      - type: picture-entity
        entity: camera.hallway_camera_mainstream
        name: video
        show_name: false
        show_state: false


# -------------------------------------------------------------
# -----------------------kitchen-------------------------------
# -------------------------------------------------------------
  - title: Kitchen
    cards:

      - type: entities
        entities:
          - entity: sensor.kitchen_kettle_state
            name: State
          - entity: binary_sensor.kitchen_kettle_power
            name: Power
          - entity: sensor.kitchen_kettle_temperature
            name: Temperature
        title: Kettle

      - type: entities
        entities:
          - entity: light.kitchen_light_1_light
            name: point1
          - entity: light.kitchen_light_2_light
            name: point2
          - entity: light.kitchen_lights_light
            name: group
        title: Light
        
      - type: entities
        entities:
          - entity: light.kitchen_bulb_1_light
            name: bulb1
          - entity: light.kitchen_bulb_2_light
            name: bulb2
          - entity: light.kitchen_bulb_3_light
            name: bulb3
          - entity: light.kitchen_bulb_4_light
            name: bulb4
          - entity: light.kitchen_bulb_5_light
            name: bulb5
          - entity: light.kitchen_bulb_6_light
            name: bulb6
          - entity: light.kitchen_chandelier_light
            name: group
        title: chandelier

      - type: entities
        entities:
          - entity: switch.kitchen_relay_1_channel_1
            name: Channel1
          - entity: switch.kitchen_relay_1_channel_2
            name: Channel2
          - entity: sensor.kitchen_relay_1_current
            name: Current
          - entity: sensor.kitchen_relay_1_energy
            name: Energy
          - entity: sensor.kitchen_relay_1_power
            name: Power
          - entity: sensor.kitchen_relay_1_voltage
            name: Voltage
        title: Ledline

      - type: entities
        entities:
          - entity: select.chunmi_press2_f189_start_cook
            name: cook
          - entity: button.chunmi_press2_f189_cancel_cooking
            name: cancel
          - entity: sensor.chunmi_press2_f189_status
            name: status
        title: Cooker

      - type: entities
        entities:
          - entity: binary_sensor.kitchen_motion_1_motion
            name: motion
          - entity: sensor.kitchen_motion_1_battery
            name: battery
          - entity: sensor.kitchen_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.kitchen_motion_2_motion
            name: motion
          - entity: sensor.kitchen_motion_2_battery
            name: battery
          - entity: sensor.kitchen_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: picture-entity
        entity: camera.kitchen_camera_mainstream
        name: video
        show_name: false
        show_state: false


# -------------------------------------------------------------
# -----------------------bathroom------------------------------
# -------------------------------------------------------------
  - title: Bathroom
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_motion_1_motion
            name: motion
          - entity: sensor.bathroom_motion_1_battery
            name: battery
          - entity: sensor.bathroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.bathroom_light_1_light
            name: point1
          - entity: light.bathroom_light_2_light
            name: point2
          - entity: light.bathroom_light_3_light
            name: point3
          - entity: light.bathroom_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: switch.bathroom_relay_1_channel_1
            name: Channel1
          - entity: switch.bathroom_relay_1_channel_2
            name: Channel2
          - entity: sensor.bathroom_relay_1_current
            name: Current
          - entity: sensor.bathroom_relay_1_energy
            name: Energy
          - entity: sensor.bathroom_relay_1_power
            name: Power
          - entity: sensor.bathroom_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: switch.bathroom_relay_2_channel_1
            name: Channel1
          - entity: switch.bathroom_relay_2_channel_2
            name: Channel2
          - entity: sensor.bathroom_relay_2_action
            name: Current
          - entity: sensor.bathroom_relay_2_energy
            name: Energy
          - entity: sensor.bathroom_relay_2_power
            name: Power
          - entity: sensor.bathroom_relay_2_voltage
            name: Voltage
        title: Towelheat


# -------------------------------------------------------------
# ------------------------toilet-------------------------------
# -------------------------------------------------------------
  - title: Toilet
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.toilet_motion_1_motion
            name: motion
          - entity: sensor.toilet_motion_1_battery
            name: battery
          - entity: sensor.toilet_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.toilet_light_1_light
            name: point1
          - entity: light.toilet_light_2_light
            name: point2
          - entity: light.toilet_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: switch.toilet_relay_1_channel_1
            name: Channel1
          - entity: switch.toilet_relay_1_channel_2
            name: Channel2
          - entity: sensor.toilet_relay_1_action
            name: action
          - entity: sensor.toilet_relay_1_current
            name: Current
          - entity: sensor.toilet_relay_1_energy
            name: Energy
          - entity: sensor.toilet_relay_1_power
            name: Power
          - entity: sensor.toilet_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_moisture
            name: moisture
          - entity: sensor.bathroom_moisture_battery
            name: battery
        title: WaterLeak


# -------------------------------------------------------------
# -----------------------balcony-------------------------------
# -------------------------------------------------------------
  - title: Balcony
    cards:

      - type: entities
        entities:
          - entity: sensor.balcony_temperature
            name: temperature
          - entity: sensor.balcony_temperature_humidity
            name: humidity
          - entity: sensor.balcony_temperature_pressure
            name: pressure
          - entity: sensor.balcony_temperature_battery
            name: battery
        title: Temperature

      - type: picture-entity
        entity: camera.balcony_camera_mainstream
        name: video
        show_name: false
        show_state: false