title: Home
views:

  - title: Toilet
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.toilet_motion_1_motion
            name: motion
          - entity: sensor.toilet_motion_1_battery
            name: battery
          - entity: sensor.toilet_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.toilet_light_1_light
            name: point1
          - entity: light.toilet_light_2_light
            name: point2
          - entity: light.toilet_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: switch.toilet_relay_1_channel_1
            name: Channel1
          - entity: switch.toilet_relay_1_channel_2
            name: Channel2
          - entity: sensor.toilet_relay_1_action
            name: action
          - entity: sensor.toilet_relay_1_current
            name: Current
          - entity: sensor.toilet_relay_1_energy
            name: Energy
          - entity: sensor.toilet_relay_1_power
            name: Power
          - entity: sensor.toilet_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_moisture
            name: moisture
          - entity: sensor.bathroom_moisture_battery
            name: battery
        title: WaterLeak
