title: Basement
views:

  - title: Basement
    cards:
      - entity: switch.outlet02_power
        type: custom:multiple-entity-row
        name: outlet02
        entities:
          - switch.outlet02