title: Basement
views:

  - title: Basement
    cards:

      - entity: switch.outlet02
        type: custom:multiple-entity-row
        name: Outlet_02
        toggle: true
        entities:
          - entity: sensor.outlet02_power
            name: power