title: Basement
views:

  - title: Basement
    cards:
      - entity: sensor.outlet02_power
        type: custom:multiple-entity-row
        name: outlet021
        entities:
          - switch.outlet02
      - entity: switch.outlet02
        type: custom:multiple-entity-row
        name: outlet022
        entities:
          - sensor.outlet02_power