title: Home
views:

  - title: Main
    cards:

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.gateway
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.canopy_left
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.canopy_main
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.court
            live_provider: go2rtc

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.garden
            live_provider: go2rtc