apiVersion: apps/v1
kind: Deployment
metadata:
  name: amur
  namespace: homeassistant
  labels:
    app: amur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amur
  template:
    metadata:
      labels:
        app: amur
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kube03
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-homeassistant-amur
      containers:
      - name: amur
        volumeMounts:
          - mountPath: "/config/.storage"
            name: storage
        image: {{ index .Values "amur" "image" "name" }}:{{ index .Values "amur" "image" "tag" }}
        imagePullPolicy: {{ index .Values "amur" "image" "pullPolicy" }}
        env:
        - name: MYSQL_URL
          valueFrom:
            secretKeyRef:
              name: mysql
              key: url
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
