apiVersion: apps/v1
kind: Deployment
metadata:
  name: amur
  namespace: homeassistant
  labels:
    app: amur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amur
  template:
    metadata:
      labels:
        app: amur
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kube03
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: amur
        image: {{ index .Values "amur" "image" "name" }}:{{ index .Values "amur" "image" "tag" }}
        imagePullPolicy: {{ index .Values "amur" "image" "pullPolicy" }}
        env:
        - name: MYSQL_URL
          valueFrom:
            secretKeyRef:
              name: mysql
              key: url
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          command: ["/bin/sh"]
          args:
          - -c
          - >-
              rm -rf /tmp/git/XiaomiGateway3 &&
              git clone git@github.com:AlexxIT/XiaomiGateway3.git /tmp/git/XiaomiGateway3 &&
              cp -r /tmp/git/XiaomiGateway3/custom_components* /config/custom_components
