apiVersion: apps/v1
kind: Deployment
metadata:
  name: amur
  namespace: homeassistant
  labels:
    app: amur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amur
  template:
    metadata:
      labels:
        app: amur
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kube03
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: amur
        image: homeassistant/amur:master
        imagePullPolicy: Always
        env:
        - name: ENV
          value: master
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
