home-assistant:
  nodeSelector: {kubernetes.io/hostname: "kube02"}
  persistence:
    config:
      enabled: true
      storageClass: local-storage
      size: 8Gi
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 8123
          nodePort: 30017