apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-homeassistant
  namespace: homeassistant-ci
spec:
  ttlStrategy:
    secondsAfterCompletion: 604800
  entrypoint: wf
  onExit: slack
  arguments:
    parameters:
    - name: service
      enum:
        - amur
    - name: env
      enum:
        - master

  templates:

    - name: wf
      steps:
      - - name: build
          template: build
          arguments:
            parameters:
            - name: project
              value: home
            - name: application
              value: homeassistant
            - name: service
              value: "{{`{{ workflow.parameters.service }}`}}"
            - name: env
              value: "{{`{{ workflow.parameters.env }}`}}"

    - name: build
      inputs:
        parameters:
        - name: project
        - name: application
        - name: service
        - name: env
      steps:
        - - name: build
            templateRef:
              name: build
              template: process
              clusterScope: true
            arguments:
              parameters:
                - name: project
                  value: "{{`{{ inputs.parameters.project }}`}}"
                - name: application
                  value: "{{`{{ inputs.parameters.application }}`}}"
                - name: service
                  value: "{{`{{ inputs.parameters.service }}`}}"
                - name: env
                  value: "{{`{{ inputs.parameters.env }}`}}"

    - name: slack
      steps:
        - - name: slack
            templateRef:
              name: slack
              template: send
              clusterScope: true
