apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-homeassistant
  namespace: homeassistant-ci
spec:
  ttlStrategy:
    secondsAfterCompletion: 604800
  entrypoint: wf
  onExit: slack
  arguments:
    parameters:
    - name: service
      enum:
        - amur
    - name: env
      enum:
        - master

  templates:

    - name: wf
      steps:
      - - name: docker
          template: docker
          templateRef:
            name: docker
            template: process
            clusterScope: true
          arguments:
            parameters:
            - name: project
              value: home
            - name: application
              value: homeassistant
            - name: service
              value: "{{`{{ workflow.parameters.service }}`}}"
            - name: env
              value: "{{`{{ workflow.parameters.env }}`}}"

    - name: slack
      steps:
        - - name: slack
            templateRef:
              name: slack
              template: send
              clusterScope: true
