#auth:
#  reset_admin_password: true
mqtt:
  enabled: False
#detectors:
#  ov_0:
#    type: openvino
#    device: CPU
#  ov_1:
#    type: openvino
#    device: CPU
record:
  enabled: True
  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 180
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
snapshots:
  enabled: True
  retain:
    default: 30
review:
  alerts:
    labels:
      - person
go2rtc:
  streams:
    madam:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.112:554?real_stream
cameras:
  madam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/madam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 1
