logger:
  default: debug

#auth:
#  reset_admin_password: true
mqtt:
  host: mosquitto
  port: 1883
  user: homeassistant
  password: FLS3GD8Qc8xJWp
#detectors:
#  ov_0:
#    type: openvino
#    device: CPU
#  ov_1:
#    type: openvino
#    device: CPU
record:
  enabled: True
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 180
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
snapshots:
  enabled: True
  retain:
    default: 30
review:
  alerts:
    labels:
      - person
go2rtc:
  log:
    exec: trace
  streams:
    madam:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.112:554/stream1#video=copy#audio=aac
    madam-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.112:554/stream2#video=copy#audio=aac
    backyard:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.113:554/stream1#video=copy#audio=aac
    backyard-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.113:554/stream2#video=copy#audio=aac
    gate-back:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.114:554/stream1#video=copy#audio=aac
    gate-back-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.114:554/stream2#video=copy#audio=aac
    gate-front:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.115:554/stream1#video=copy#audio=aac
    gate-front-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.115:554/stream2#video=copy#audio=aac
    stairway:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.116:554/stream1#video=copy#audio=aac
    room05:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.117:554/stream1#video=copy#audio=aac
    room05-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.117:554/stream2#video=copy#audio=aac
    room08:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.118:554/stream1#video=copy#audio=aac
    room08-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.118:554/stream2#video=copy#audio=aac
    stairway-sub:
      - ffmpeg:rtsp://homeassistant:aP5n8XdebfKeDn@192.168.4.116:554/stream2#audio=aac#video=h264#rotate=270
cameras:
  room05:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/room05
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/room05-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
#      listen:
#        - speech
    detect:
      fps: 4
  room08:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/room08
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/room08-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
#      listen:
#        - speech
    detect:
      fps: 4
  madam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/madam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/madam-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 4
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 4
  gate-back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate-back
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate-back-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 4
  gate-front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate-front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate-front-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 4
#    review:
#      alerts:
#        required_zones:
#          - canopy
#    zones:
#      canopy:
#        coordinates: 0,1,1,1,1,0.395,0,0.39
  stairway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stairway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stairway-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    audio:
      enabled: True
    detect:
      fps: 1
