version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
#      - ./mosquitto:/etc/mosquitto
      - /docker/iot-mosquitto-dacha/config:/mosquitto/config