frigate:
  nodeSelector: {kubernetes.io/hostname: "kube03"}
  service:
    type: ClusterIP
  config: |
    mqtt:
      host: "mosquitto.mosquitto"
      port: 1883
      user: homeassistant
      password: "FLS3GD8Qc8xJWp"
    cameras:
      vestibule:
        onvif:
          host: 192.168.2.113
          port: 80
          user: homeassistant
          password: aP5n8XdebfKeDn