frigate:
  nodeSelector: {kubernetes.io/hostname: "kube03"}
  service:
    # bug with NodePort assigne same port for all services
    type: ClusterIP
  persistence:
    config:
      enabled: true
      existingClaim: home-frigate-amur-config
    media:
      enabled: true
      existingClaim: home-frigate-amur-media
  config: |
    mqtt:
      host: "mosquitto.mosquitto"
      port: 1883
      user: homeassistant
      password: "FLS3GD8Qc8xJWp"
    record:
      enabled: True
      retain:
        days: 2
        mode: all
    snapshots:
      enabled: True
      retain:
        default: 30
    audio:
      enabled: True
    go2rtc:
      streams:
        elevators: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.111:80
        vestibule: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.113:80
        intercom: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.116:80
        balcony: onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.117:80
    cameras:
      elevators:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/elevators
              input_args: preset-rtsp-restream
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 2
      vestibule:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.113:554/Streaming/Channels/101
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 2
      intercom:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.116:554/Streaming/Channels/101
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 3
      balcony:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.117:554/Streaming/Channels/101
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 1