frigate:
  nodeSelector: {kubernetes.io/hostname: "kube03"}
  service:
    # bug with NodePort assigne same port for all services
    type: ClusterIP
  persistence:
    config:
      enabled: true
      existingClaim: home-frigate-amur-config
    media:
      enabled: true
      existingClaim: home-frigate-amur-media
  config: |
    mqtt:
      host: "mosquitto.mosquitto"
      port: 1883
      user: homeassistant
      password: "FLS3GD8Qc8xJWp"
    record:
      enabled: True
      retain:
        days: 2
        mode: all
    snapshots:
      enabled: True
      retain:
        default: 30
    audio:
      enabled: True
    cameras:
      elevators:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.111:554/live.sdp
              roles:
                - record
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.111:554/live2.sdp
              roles:
                - detect
                - audio
        detect:
          fps: 2
      vestibule:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.113:554/Streaming/Channels/101
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 2
      intercom:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.116:554/Streaming/Channels/101
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 3
      balcony:
        ffmpeg:
          inputs:
            - path: rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.117:554/Streaming/Channels/101
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 1