apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    mqtt:
      host: "mosquitto.mosquitto"
      port: 1883
      user: homeassistant
      password: "FLS3GD8Qc8xJWp"
    record:
      enabled: True
      retain:
        days: 2
        mode: all
    snapshots:
      enabled: True
      retain:
        default: 30
    go2rtc:
      streams:
        elevators:
    #      - onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.111:80
          - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.111:554/live.sdp
        vestibule:
    #      - onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.113:80
          - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.113:554/Streaming/Channels/101
        intercom:
    #      - onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.116:80
          - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.116:554/Streaming/Channels/101
          - "ffmpeg:intercom#audio=aac"
        balcony:
    #      - onvif://homeassistant:aP5n8XdebfKeDn@192.168.2.117:80
          - rtsp://homeassistant:aP5n8XdebfKeDn@192.168.2.117:554/Streaming/Channels/101
          - "ffmpeg:balcony#audio=aac"
    cameras:
      elevators:
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-rtsp:8554/elevators
              input_args: preset-rtsp-restream
              roles:
                - record
                - detect
                - audio
          output_args:
            record: preset-record-generic-audio-copy
        audio:
          enabled: True
        detect:
          fps: 2