apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    mqtt:
      host: "mosquitto.mosquitto"
      port: 1883
      user: homeassistant
      password: "FLS3GD8Qc8xJWp"
    record:
      enabled: True
      retain:
        days: 2
        mode: all
    snapshots:
      enabled: True
      retain:
        default: 30
    audio:
      enabled: True
    cameras:
      elevators:
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-rtsp:8554/elevators
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 2
      vestibule:
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-rtsp:8554/vestibule
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 2
      intercom:
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-rtsp:8554/intercom
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 3
      balcony:
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-rtsp:8554/balcony
              roles:
                - record
                - detect
                - audio
        detect:
          fps: 1