apiVersion: v1
kind: Service
metadata:
  name: frigate-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: NodePort
  ports:
    - name: https
      port: 8971
      nodePort: 30024
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-endpoint
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: go2rtc-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 1984
    targetPort: 1984
    protocol: TCP
  selector:
    app: frigate
