apiVersion: v1
kind: Service
metadata:
  name: frigate-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "false"
spec:
  type: NodePort
  ports:
  - port: 8973
    nodePort: 30024
  selector:
    app: frigate
